### ISSUE TITLE
Do not FORCE_FILESYSTEM=1

### ISSUE THREAD

**Issue by adishavit** [biggzlar/opencv_js_compiler#3]
The build args have `emcc_args = '-s FORCE_FILESYSTEM=1`.  
According to the [docs](https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html#including-file-system-support):

> Emscripten decides whether to include file system support automatically. Many programs don’t need files, and **file system support is not negligible in size**, so Emscripten avoids including it when it doesn’t see a reason to. That means that if your C/C++ code does not access files, then the FS object and other file system APIs will not be included in the output. And, on the other hand, if your C/C++ code does use files, then file system support will be automatically included. So normally things will “just work” and you don’t need to think about this at all.

Consider removing this from default build args, and maybe make it into an opt-in command line option.

**Comment by adishavit** [comment]
For some reason, even after removing it and removing all the called to FS in the cpp and html, the resulting js file size is the same.

**Comment by biggzlar** [comment]
This was an added demo of the virtual filesystem and how to interact with it. Removed those features from the example.cpp and index.html because they are not relevant for the current project.

**Comment by biggzlar** [comment]
By the way: no idea why the size remains the same...

**Comment by adishavit** [comment]
So will you be making a commit that removes this?
