### ISSUE TITLE
Emscripten Version Issue - emscripten.Building.make(['make','-j4'])

### ISSUE THREAD

**Issue by Neuroforge** [biggzlar/opencv_js_compiler#7]
Hello,

This project looks amazing.

However, when building the example.cpp application there was an error on line 157 of n_make.py

`emscripten.Building.make(['make', '-j4'])`

This occurs at around 33% of the OpenCV build.

> [ 33%] Built target libprotobuf
> Scanning dependencies of target ittnotify
> [ 33%] Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/ittnotify_static.c.o
> In file included from /Users/daniel/Documents/opencv_js_compiler/opencv/3rdparty/ittnotify/src/ittnotify/ittnotify_static.c:59:
> /Users/daniel/Documents/opencv_js_compiler/opencv/3rdparty/ittnotify/src/ittnotify/ittnotify_config.h:370:12: error: implicit declaration of function '__TBB_machine_fetchadd4' is
> invalid in C99 [-Werror,-Wimplicit-function-declaration]
> return __TBB_machine_fetchadd4(ptr, 1) + 1L;
> ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/3rdparty/ittnotify/src/ittnotify/ittnotify_config.h:370:12: warning: this function declaration is not a prototype [-Wstrict-prototypes]
> 1 warning and 1 error generated.
> ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
> make[2]: *** [3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/ittnotify_static.c.o] Error 1
> make[1]: *** [3rdparty/ittnotify/CMakeFiles/ittnotify.dir/all] Error 2
> make: *** [all] Error 2
> Traceback (most recent call last):
> File "n_make.py", line 159, in 
> emscripten.Building.make(['make', '-j4'])
> File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/shared.py", line 1558, in make
> raise subprocess.CalledProcessError(cmd=args, returncode=process.returncode)
> subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
> 

Note: I have built OpenCV on it's own using cmake and it worked ok.

I can build OpenCV on it's own.
I can build OpenCVjs from their platform folder.
This would indicate an emscripten problem. Any thoughts or experience with this issue?

Similar issue here - kripken/emscripten#5298

LLVM root is correct in ./emscripten

Which version of Emscripten did you use when compiling your example.cpp?

**Comment by Neuroforge** [comment]
Switching to opencv 3.1.0 fixed this issue.

git checkout 3.1.0

**Comment by biggzlar** [comment]
Awesome, thank you for pointing it out.
